// testParkingTicketSimulator.cpp : This file will test the parkedCar, parkingMeter, policeOfficer,
// and parkingTicket objects and their respecitve member functions. A parkingTicket object will be 
// generated by a policeOfficer object ONLY when the member variable minParked in the parkedCar object
// is greated than the member variable minPurchased in the parkingMeter object.

#include <iostream>
#include "ParkedCar.h"
#include "ParkingMeter.h"
#include "PoliceOfficer.h"

using namespace std;

int main()
{
	ParkedCar myCar;
	ParkingMeter myMeter;
	cout << "myCar minutes: " << myCar.getMin() << endl;
	cout << "myMeter minutes: " << myMeter.getMin() << endl;
	PoliceOfficer myOfficer;
	cout << "myOfficer name: " << myOfficer.getName() << endl;
	myOfficer.isExpired(myCar, myMeter);
}


